<?xml version='1.0' encoding='UTF-8'?><wsdl:definitions xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://price.hotel.com/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:ns1="http://schemas.xmlsoap.org/soap/http" name="PriceServiceService" targetNamespace="http://price.hotel.com/">
  <wsdl:types>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://price.hotel.com/" elementFormDefault="unqualified" targetNamespace="http://price.hotel.com/" version="1.0">

  <xs:element name="getPrice" type="tns:getPrice"/>

  <xs:element name="getPriceResponse" type="tns:getPriceResponse"/>

  <xs:complexType name="getPrice">
    <xs:sequence>
      <xs:element minOccurs="0" name="arg0" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="getPriceResponse">
    <xs:sequence>
      <xs:element name="return" type="xs:double"/>
    </xs:sequence>
  </xs:complexType>

</xs:schema>
  </wsdl:types>
  <wsdl:message name="getPriceResponse">
    <wsdl:part element="tns:getPriceResponse" name="parameters">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="getPrice">
    <wsdl:part element="tns:getPrice" name="parameters">
    </wsdl:part>
  </wsdl:message>
  <wsdl:portType name="PriceService">
    <wsdl:operation name="getPrice">
      <wsdl:input message="tns:getPrice" name="getPrice">
    </wsdl:input>
      <wsdl:output message="tns:getPriceResponse" name="getPriceResponse">
    </wsdl:output>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="PriceServiceServiceSoapBinding" type="tns:PriceService">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="getPrice">
      <soap:operation soapAction="" style="document"/>
      <wsdl:input name="getPrice">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="getPriceResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="PriceServiceService">
    <wsdl:port binding="tns:PriceServiceServiceSoapBinding" name="PriceServicePort">
      <soap:address location="http://192.168.10.61:8080/HotelService/PriceService"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>